### ISSUE TITLE
Accepting unlimited invalid inputs

### ISSUE THREAD

**Issue by dainvinc** [mitinsharma/MSCS721-roomScheduler#1]
![unlimited inputs](https://cloud.githubusercontent.com/assets/24849870/23532616/42a905d4-ff7a-11e6-9e01-114169f96cad.JPG)
Whenever a user enters incorrect input, it keeps asking please enter valid input. Maybe exiting the loop after few attempts would be helpful?

**Comment by mitinsharma** [comment]
Issue fixed!
