### ISSUE TITLE
Did not execute "Subject?" - scheduleRoom()

### ISSUE THREAD

**Issue by dainvinc** [mitinsharma/MSCS721-roomScheduler#2]
![nosubject](https://cloud.githubusercontent.com/assets/24849870/23532605/33c6c1fa-ff7a-11e6-877a-8c4d1ca2b30e.JPG)
The scheduleRoom() method does not accept the input for the subject as it seems like it is skipping the step.

**Comment by mitinsharma** [comment]
Fixed!
